### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kimmy100b** [doozi316/master-popular-technique#3]
# maven 버전확인 오류
- cmd에서 `mvn -v`을 입력했을 때 오류발생
- 'mvn'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는 배치 파일이 아닙니다.
<br/>
<br/>

# 스크린 샷
![mvnerror jpg](https://user-images.githubusercontent.com/59406612/77727232-2a1bc380-703d-11ea-8e8a-19357a6ce999.png)
<br/>
<br/>

# 시나리오
- maven을 설치한 후 cmd에서 버전을 확인하려고 할 때 오류가 난다.
<br/>
<br/>

# 해결방안
1. cmd창에서 `set %MAVEN_HOME%\bin`을 실행
2. cmd창에서 `set MAVEN_HOME=[maven의 path 입력]`을 실행
3. JAVA_HOME도 path가 정확한 지 환경변수를 다시 한번 확인해주기
(환경 변수에서 JAVA_HOME이 MAVEN_HOME보다 위에 있어야한다)
4. 필요한 경우, set %JAVA_HOME%\bin 과 set JAVA_HOME=[java의 path 입력]을 cmd 창에서 명령을 실행
5. cmd 창을 새로 열어서 'mvn -v'를 입력하면 오류 해결

<br/>
<br/>

# 개발 환경
- maven : 3.6.3
- jdk : 13.0.2
<br/>
<br/>

# 기타 할 말
- 어떤 방식을 실행해서 오류를 해결했는 지는 정확하게 모르지만 위와 같은 방식을 실행하니 오류가 해결됨

<br/>
<br/>

# 참조
- [MAVEN 설치](https://freestrokes.tistory.com/35)
- [cmd환경변수설정](https://seodaeya.tistory.com/115)
- [cmd java환경변수설정](https://kjyun.tistory.com/81)

<br/>
<br/>

**Comment by doozi316** [comment]
조아조아 아주 므쪄용~!
